peercoin support
trezor/connect pull request #505
Opened 2019-12-06 12:14 UTC by backpacker69

this should add peercoin support to connect js library

2019-12-09 15:47 UTC, szymonlesisz requested changes

2019-12-09 15:47 UTC, szymonlesisz commented on Makefile
> +	../trezor-firmware/common/tools/cointool.py dump -p -d connect -e icon -e cooldown -e github -e key -e maintainer -e uri_prefix -e version_group_id -e website -e links -e duplicate -e wallet -e bitc
do not change the path to submodule, connect is strictly bound with commit in "trezor-common" submodule
To regenerate coins this submodule needs to be updated first

2019-12-09 15:47 UTC, szymonlesisz commented on src/js/data/CoinInfo.js
> +            decimals: coin.divisibility,
I've opened issue about [names inconsistency](https://github.com/trezor/trezor-firmware/issues/743) and it will be changed

2019-12-10 10:39 UTC, szymonlesisz commented
I've already bump coins.json with peercoin and `decimals` field. Pls rebase

2019-12-10 11:29 UTC, backpacker69 commented
> I've already bump coins.json with peercoin and `decimals` field. Pls rebase

thank you, rebased and force pushed

2019-12-11 14:03 UTC, merged

2019-12-11 14:07 UTC, szymonlesisz commented
i needed to add peercoin support to [@trezor/utxo-lib](https://github.com/trezor/trezor-utxo-lib/commit/28dd4e174e22c2b5386730068b5474507d107570)

also you had [invalid timestamps](https://github.com/trezor/connect/commit/f0cb61e0ca828a4177e87cfa9be398553fbae589) in tests fixtures

will be released tomorrow together with zcash fork fix

2019-12-11 14:10 UTC, backpacker69 commented
thank you!

2019-12-11 16:24 UTC, szymonlesisz commented
released as 8.0.12