allow path 49 unhardened
trezor/connect pull request #646
Opened 2020-08-10 18:15 UTC by logansease

At Casa, we use unhardened paths for our multisig addresses, specifically 49/{0,1}/X/X/X
We use unhardened paths so that we can derive paths for multiple coin types and accounts on our server, without requiring the private key or user export of their device.
In Trezor-Connect v6, we have not had any problems with our multisig implementation, but in v8 we are having issues with our change addresses.
Specifically, the change output fails validation when we provide the device the node and script information required for the trezor device to authorize the the change output without user interaction.

Upon a deep dive into the trezor code, I see that this fails because the output validation does the following:

determine the script type for validation based on the Hardened path provided to the output
if the path found is not a hardened path of the types allowed, then the output script type is assumed to be 'PAYTOADDRESS'
the script for that output is then recomputed based on the information supplied and the type computed and compared against the provided script for validation.
The issue we are having is that we are using the script type 'PAYTOP2SHWITNESS', with unhardened paths. When the validation function determines the script type based on the hardened path, the unhardened path we provide does not fall into a case provided by the getScriptType function, and the default script type of 'PAYTOADDRESS' is used instead. When the validation function then computes the script based on PAYTOADDRESS, validation fails because the PAYTOADDRESS script computed does not match our provided PAYTOP2SHWITNESS script.

The solution I propose is quite simple. Rather than only checking for a hardened 49 path to get PAYTOP2SHWITNESS, if the raw (unhardened) path is 49 also return PAYTOP2SHWITNESS.

This will result in the getScriptType for our specific input returning PAYTOP2SHWITNESS which will then allow validation to validate with our expected script type and succeed.

2020-08-11 09:04 UTC, szymonlesisz commented
what about other paths starting with 44 or 84?
are you aware that using non standard path check inside trezor firmware will also fail if `safety-checks` is not enabled?

2020-08-11 09:16 UTC, prusnak commented
> what about other paths starting with 44 or 84?

I think Casa uses only 49; at least that's what we've been told earlier when we were adding the exception to the firmware here:

https://github.com/trezor/trezor-firmware/blob/5536fbb98a8214279d6d45052d1c30109f5f79a7/core/src/apps/bitcoin/keychain.py#L45-L46

>  are you aware that using non standard path check inside trezor firmware will also fail if safety-checks flag is not disabled?

This is something I told you earlier, but I was wrong. Because of the rule exception mentioned above, this should work without turned-off safety checks. Sorry about misleading you earlier.

2020-08-11 09:19 UTC, prusnak requested changes

2020-08-11 09:19 UTC, prusnak commented on src/js/utils/pathUtils.js
> +     // allow an unhardened 49 path to use paytop2shwitness
```suggestion
     // compatibility for Casa - allow an unhardened 49 path to use paytop2shwitness
```

2020-08-11 09:22 UTC, szymonlesisz commented on src/js/utils/pathUtils.js
> +     // allow an unhardened 49 path to use paytop2shwitness
nitpick: paytop2shwitness > payto2shwitness

2020-08-11 12:08 UTC, logansease commented
That’s great and very much appreciated. We will look to move to 49 hardened in the future but this is very helpful until then. 
And yes we only use 49. To keep the PR scope as limited as possible I did not include 44 or 84 since we do not use those.

2020-08-11 13:06 UTC, merged

2020-08-12 10:54 UTC, prusnak commented
@logansease fix pushed to production (connect.trezor.io)

2020-08-12 11:11 UTC, logansease commented
Thank you!

2020-08-12 18:10 UTC, logansease commented
@prusnak Hey Pavol, I must be missing something. I'm not seeing the expected behavior from the new code in the new release, and  searching through the js files I don't see any references to the function I changed getOutputScriptType, nor to 'scripts differ' error I see. 
I've looked in:
 https://connect.trezor.io/8/trezor-connect.js, 
https://connect.trezor.io/8/js/iframe.ecfb9f15524efd814879.js, https://connect.trezor.io/8/js/popup.ecfb9f15524efd814879.js


Does this code in helpers/pathUtils.js even make its way into the connect build? Or does this change need to be made to the firmware or core libraries for it to persist? 

Thanks for your help.

2020-08-12 20:29 UTC, prusnak commented
@logansease I can see `if(49===e[0])return"PAYTOP2SHWITNESS";` which is the minimized version of your change in both https://connect.trezor.io/8/js/iframe.ecfb9f15524efd814879.js and https://connect.trezor.io/8/js/popup.ecfb9f15524efd814879.js

2020-08-12 22:57 UTC, logansease commented
Shoot. I am still getting 'verifyTx: Output 1 scripts differ' (where output 1 is our change address) when I use the code that used to work on trezor connect v6. 
Will continue to dive in--- if you happen to have any ideas they'd be greatly appreciated
```
            address_n: [account.keyPathPurpose, account.keyPathCoinType, keyPathAccount, changePath(true), tx.changeAddressPath],
            script_type: 'PAYTOP2SHWITNESS',
            multisig: {pubkeys: outputNodes, signatures: emptySigs, m: account.requiredSignatures}
```

2020-08-13 12:52 UTC, szymonlesisz commented
connect 6 didn't have script_type checks and signTx verification implemented, so obviously it was working but it doesn't mean it was working as expected :)

your code is failing here:
https://github.com/trezor/connect/blob/develop/src/js/core/methods/helpers/signtxVerify.js#L137
>>
https://github.com/trezor/connect/blob/develop/src/js/core/methods/helpers/signtxVerify.js#L71

what this part of the code does?

it's trying to [generate public key](https://github.com/trezor/connect/blob/develop/src/js/core/methods/helpers/signtxVerify.js#L84) on Trezor from given `address_n` and then [derive output script hash](https://github.com/trezor/connect/blob/develop/src/js/core/methods/helpers/signtxVerify.js#L96) from it

both previously signed and derived script hash should be the same, but for some reason they are not

you should probably [run own instance of connect](https://github.com/trezor/connect/blob/develop/docs/index.md#running-local-version-developstable) and test it locally first

2020-08-13 14:38 UTC, szymonlesisz commented
quick question: does `multisig` field needs to be defined in the output? because in this case script_type should be `PAYTOMULTISIG` not `PAYTOP2SHWITNESS`

i've run quick test with output PAYTOP2SHWITNESS and unhardended path 49 and it DOES work when `multisig` field is not provided (but im not sure if tx is valid tho)

2020-08-13 14:47 UTC, logansease commented
Thanks for taking a moment to help me figure this out. We do need to use the multisig field, because this is a 3of5 multisig transaction with the addresses of the type P2SH_P2WSH.

Here is the code used to derive the nodes that are passed into the multisig param if it is helpful-- 
We essentially take the 5 xpubs from our multisig addresses, convert them to hd nodes and then derive the public keys at the correct path off those xpubs. 

We know this code is generally correct, as in trezor 6, it would send the change to the expected address without confirmation--- it is just a matter of how to make it pass this new validation.

```
  function getNodes(keys, address) {
    let sortedKeys = [];
    let nodes = [];

    // Derive public key for each key object
    keys.forEach(key => {
      let node = HD.fromBase58(key.xpub);
      let derive = node.derive(address.isChange === true ? 1 : 0).derive(address.keyPathAddress);
      let pk = derive.publicKey.toString('hex');
      key.publicKey = pk;
      sortedKeys.push(key);
    });

    // Perform lexicographic sorting
    sortedKeys.sort((a, b) => a.publicKey.localeCompare(b.publicKey));

    // create the pub key array to assign to each input
    sortedKeys.forEach(key => nodes.push({node: xpubToHDNodeType(key.xpub), address_n: [changePath(address.isChange), address.keyPathAddress]}));

    return nodes;
  }
```

2020-08-13 14:58 UTC, szymonlesisz commented
more helpful would be a full json sent to connect without variables and derivation/calculation

2020-08-13 15:19 UTC, logansease commented
Absolutely!
Here are two examples

```
TrezorConnect.signTransaction({

inputs: [{“address_n":[49,1,82,0,10],"prev_index":1,"prev_hash":"e7f60596ec84d2d7532fa9a6dd6234dd775414d930fe078e15c4e87c8f82e45f","amount":"2078993","script_type":"SPENDP2SHWITNESS","multisig":{"pubkeys":[{"node":{"depth":3,"child_num":82,"fingerprint":3903176541,"public_key":"032745c4b6193d0e517b80cc5416fe834704bbf63de148f048964cb4cd59215b82","chain_code":"493c4396a7035f9bb2d148cd7bb89c72d26ee8eb8f7a93bf49732460229abdb3"},"address_n":[0,10]},{"node":{"depth":3,"child_num":82,"fingerprint":1829152189,"public_key":"03acd4be1ded0177a710dc257b70ee5278310af3df9c4348f7716997e003712f33","chain_code":"b8096c0287ab37bc3bded11907f7ce4eef04079b03196b98f023db3d0e536573"},"address_n":[0,10]},{"node":{"depth":3,"child_num":82,"fingerprint":2846048664,"public_key":"03aa1483788a0a6cd9ed77cf6d9fc86cf241fd506dec65f4d9a29abb801228e136","chain_code":"b551fe55193aa1d28b370c0d68f95d67aaae6a46409e5854136772ad47dac7dc"},"address_n":[0,10]},{"node":{"depth":3,"child_num":82,"fingerprint":795513328,"public_key":"029d8899e1b23b24f710151ca44bd6a21ddeeed76495b06cb09b0b6bccfff78bc8","chain_code":"045bbce0662f81faf59ff7868d1faf670dac0296cb200bfc3b8633298292516c"},"address_n":[0,10]},{"node":{"depth":3,"child_num":996,"fingerprint":1206541601,"public_key":"0393a06919a90146bd88082ea2d3afd8eed0f8c6272d98ed76879a98a2c49dfe54","chain_code":"a0551650ade0ba9fc420054e02d7d4f8558fc85e409351a483f20a0b5744349e"},"address_n":[0,10]}],"signatures":[],"m":3}}]



outputs: [{“address":"2NC6AREzM5T35mfVcTV4RACnSyarhy5kJpz","amount":"43527","script_type":"PAYTOADDRESS"},{"amount":"2034888","address_n":[49,1,82,1,1],"script_type":"PAYTOP2SHWITNESS","multisig":{"pubkeys":[{"node":{"depth":3,"child_num":82,"fingerprint":1829152189,"public_key":"03acd4be1ded0177a710dc257b70ee5278310af3df9c4348f7716997e003712f33","chain_code":"b8096c0287ab37bc3bded11907f7ce4eef04079b03196b98f023db3d0e536573"},"address_n":[1,1]},{"node":{"depth":3,"child_num":82,"fingerprint":3903176541,"public_key":"032745c4b6193d0e517b80cc5416fe834704bbf63de148f048964cb4cd59215b82","chain_code":"493c4396a7035f9bb2d148cd7bb89c72d26ee8eb8f7a93bf49732460229abdb3"},"address_n":[1,1]},{"node":{"depth":3,"child_num":82,"fingerprint":795513328,"public_key":"029d8899e1b23b24f710151ca44bd6a21ddeeed76495b06cb09b0b6bccfff78bc8","chain_code":"045bbce0662f81faf59ff7868d1faf670dac0296cb200bfc3b8633298292516c"},"address_n":[1,1]},{"node":{"depth":3,"child_num":82,"fingerprint":2846048664,"public_key":"03aa1483788a0a6cd9ed77cf6d9fc86cf241fd506dec65f4d9a29abb801228e136","chain_code":"b551fe55193aa1d28b370c0d68f95d67aaae6a46409e5854136772ad47dac7dc"},"address_n":[1,1]},{"node":{"depth":3,"child_num":996,"fingerprint":1206541601,"public_key":"0393a06919a90146bd88082ea2d3afd8eed0f8c6272d98ed76879a98a2c49dfe54","chain_code":"a0551650ade0ba9fc420054e02d7d4f8558fc85e409351a483f20a0b5744349e"},"address_n":[1,1]}],"signatures”:[“”,””,””,””,””],”m”:3}}],

coin: "TEST"
}
```

```
TrezorConnect.signTransaction({
inputs: [
  {
    "address_n": [
      49,
      1,
      82,
      0,
      3
    ],
    "prev_index": 1,
    "prev_hash": "01844747e0845f5a10f688f40490984a7cd47c3ea5c4897e4ca5cdf30544aa39",
    "amount": "12844",
    "script_type": "SPENDP2SHWITNESS",
    "multisig": {
      "pubkeys": [
        {
          "node": {
            "depth": 3,
            "child_num": 82,
            "fingerprint": 1829152189,
            "public_key": "03acd4be1ded0177a710dc257b70ee5278310af3df9c4348f7716997e003712f33",
            "chain_code": "b8096c0287ab37bc3bded11907f7ce4eef04079b03196b98f023db3d0e536573"
          },
          "address_n": [
            0,
            3
          ]
        },
        {
          "node": {
            "depth": 3,
            "child_num": 996,
            "fingerprint": 1206541601,
            "public_key": "0393a06919a90146bd88082ea2d3afd8eed0f8c6272d98ed76879a98a2c49dfe54",
            "chain_code": "a0551650ade0ba9fc420054e02d7d4f8558fc85e409351a483f20a0b5744349e"
          },
          "address_n": [
            0,
            3
          ]
        },
        {
          "node": {
            "depth": 3,
            "child_num": 82,
            "fingerprint": 3903176541,
            "public_key": "032745c4b6193d0e517b80cc5416fe834704bbf63de148f048964cb4cd59215b82",
            "chain_code": "493c4396a7035f9bb2d148cd7bb89c72d26ee8eb8f7a93bf49732460229abdb3"
          },
          "address_n": [
            0,
            3
          ]
        },
        {
          "node": {
            "depth": 3,
            "child_num": 82,
            "fingerprint": 2846048664,
            "public_key": "03aa1483788a0a6cd9ed77cf6d9fc86cf241fd506dec65f4d9a29abb801228e136",
            "chain_code": "b551fe55193aa1d28b370c0d68f95d67aaae6a46409e5854136772ad47dac7dc"
          },
          "address_n": [
            0,
            3
          ]
        },
        {
          "node": {
            "depth": 3,
            "child_num": 82,
            "fingerprint": 795513328,
            "public_key": "029d8899e1b23b24f710151ca44bd6a21ddeeed76495b06cb09b0b6bccfff78bc8",
            "chain_code": "045bbce0662f81faf59ff7868d1faf670dac0296cb200bfc3b8633298292516c"
          },
          "address_n": [
            0,
            3
          ]
        }
      ],
      "signatures": [],
      "m": 3
    }
  },
  {
    "address_n": [
      49,
      1,
      82,
      0,
      3
    ],
    "prev_index": 0,
    "prev_hash": "c79ca71d1e6c6e7574a0994736146e275dd36e5c1f09758940242d0ad2e7e85d",
    "amount": "12824",
    "script_type": "SPENDP2SHWITNESS",
    "multisig": {
      "pubkeys": [
        {
          "node": {
            "depth": 3,
            "child_num": 82,
            "fingerprint": 1829152189,
            "public_key": "03acd4be1ded0177a710dc257b70ee5278310af3df9c4348f7716997e003712f33",
            "chain_code": "b8096c0287ab37bc3bded11907f7ce4eef04079b03196b98f023db3d0e536573"
          },
          "address_n": [
            0,
            3
          ]
        },
        {
          "node": {
            "depth": 3,
            "child_num": 996,
            "fingerprint": 1206541601,
            "public_key": "0393a06919a90146bd88082ea2d3afd8eed0f8c6272d98ed76879a98a2c49dfe54",
            "chain_code": "a0551650ade0ba9fc420054e02d7d4f8558fc85e409351a483f20a0b5744349e"
          },
          "address_n": [
            0,
            3
          ]
        },
        {
          "node": {
            "depth": 3,
            "child_num": 82,
            "fingerprint": 3903176541,
            "public_key": "032745c4b6193d0e517b80cc5416fe834704bbf63de148f048964cb4cd59215b82",
            "chain_code": "493c4396a7035f9bb2d148cd7bb89c72d26ee8eb8f7a93bf49732460229abdb3"
          },
          "address_n": [
            0,
            3
          ]
        },
        {
          "node": {
            "depth": 3,
            "child_num": 82,
            "fingerprint": 2846048664,
            "public_key": "03aa1483788a0a6cd9ed77cf6d9fc86cf241fd506dec65f4d9a29abb801228e136",
            "chain_code": "b551fe55193aa1d28b370c0d68f95d67aaae6a46409e5854136772ad47dac7dc"
          },
          "address_n": [
            0,
            3
          ]
        },
        {
          "node": {
            "depth": 3,
            "child_num": 82,
            "fingerprint": 795513328,
            "public_key": "029d8899e1b23b24f710151ca44bd6a21ddeeed76495b06cb09b0b6bccfff78bc8",
            "chain_code": "045bbce0662f81faf59ff7868d1faf670dac0296cb200bfc3b8633298292516c"
          },
          "address_n": [
            0,
            3
          ]
        }
      ],
      "signatures": [],
      "m": 3
    }
  },
  {
    "address_n": [
      49,
      1,
      82,
      0,
      3
    ],
    "prev_index": 1,
    "prev_hash": "f3c435f87ded52a50a6c9316e3cbbe359926b035fba0460131ae2502e5e38180",
    "amount": "12812",
    "script_type": "SPENDP2SHWITNESS",
    "multisig": {
      "pubkeys": [...]

2020-08-13 17:46 UTC, prusnak commented
At first glance you should be using `SPENDMULTISIG` instead of `SPENDP2SHWITNESS`.

2020-08-13 17:49 UTC, prusnak commented
So I guess we need to patch both `getScriptType` and `getOutputScriptType` to return `SPENDMULTISIG` resp. `PAYTOMULTISIG` if path matches Casa path.

2020-08-13 17:52 UTC, prusnak commented
I created new PR to address this: https://github.com/trezor/connect/pull/650

2020-08-13 18:03 UTC, szymonlesisz commented
i'm looking at it right now and it will be more complex than that.
Trezor itself signs transaction correctly (i suppose), it didn't fail during signing and it returns serialized transaction.
However there is an additional script (verifytx) which double-checks this serialized transaction (inputs and outputs, links above) and it tries to derive output script from given `address_n` and compares it with output script from transaction signed by Trezor
And this script doesn't work correctly if `output.multisig` is set

2020-08-13 18:32 UTC, szymonlesisz commented
verifyTx for PAYTOMULTISIG outputs are temporary disabled in PR from @prusnak 

@logansease pls change your script_type to `SPENDMULTISIG` and `PAYTOMULTISIG` and  test it with your [local version of connect](https://github.com/trezor/connect/blob/develop/docs/index.md#running-local-version-developstable) and if it works then we will merge and release it

2020-08-14 20:26 UTC, logansease commented
@szymonlesisz Please see: https://github.com/trezor/connect/pull/652