feat(ci): automate production and beta releases to npm registry
trezor/connect pull request #847
Opened 2021-07-14 11:42 UTC by vdovhanych

This pr will allow us to publish releases to the npm registry with a simple button press. We will have 2 jobs one for production running only on v8 branch and beta one for all other branches with an option to upload beta tag packages.

2021-07-14 11:48 UTC, szymonlesisz approved these changes

2021-07-16 15:40 UTC, vdovhanych commented
I have done some checks that @szymonlesisz  was asking for but I'm not really sure it's what he wanted. Check it if it's something you think we can work with and let me know. Yes, there is one small script in js that will check the local and remote versions, I think it's really not that great from me so I would appreciate any suggestions :)

2021-07-19 11:22 UTC, tomasklim requested changes
+ add `compare-versions`

2021-07-19 11:22 UTC, tomasklim commented on scripts/ci-compare-version.js
> +var compareVersions = require('compare-versions');
```suggestion
const compareVersions = require('compare-versions');
```

2021-07-19 11:22 UTC, tomasklim commented on .github/workflows/version_check.yml
> +            npm i compare-versions
add to `package.json`

2021-07-19 11:22 UTC, tomasklim commented on .github/workflows/version_check.yml
> +            npm install
we use `yarn`

2021-07-20 07:36 UTC, tomasklim approved these changes

2021-07-20 08:45 UTC, tsusanka commented
@vdovhanych squash and force push? And let's merge

2021-07-20 14:25 UTC, tsusanka commented
See here why the CI fails. https://github.com/trezor/connect/pull/848#issuecomment-883409848

2021-07-20 14:29 UTC, tsusanka approved these changes
LGTM, though @vdovhanych haven't we agreed we will prefer Gitlab over Github Actions? :) But let's leave it like this for now, it is OK

2021-07-20 14:37 UTC, vdovhanych commented
Yes, @tsusanka I wanted to do it in Gitlab CI but it was not possible to do what we wanted. That is to run these checks on a pull requests to a v8 branch and as we do not push into the GitLab there is no other way. If we had these checks on Gitlab they would either run all the time which would mean that the pipeline would fail most of the time or we would have them run on push to a v8 branch but that doesn't provide us with preventing incorrect versioning in the v8 branch.

2021-07-20 14:44 UTC, merged