feat(cardano): add support for multisig
trezor/connect pull request #920
Opened 2021-10-15 12:47 UTC by davidmisiak

This PR adds support for Cardano native scripts and token minting. Relevant firmware PR [here](https://github.com/trezor/trezor-firmware/pull/1772).

There should be no breaking changes. New features:
- `cardanoGetNativeScriptHash` call ([docs](../blob/276ad461774e78ad8d46d6c9138c2e2cae682b4b/docs/methods/cardanoGetNativeScriptHash.md))
- multi-sig transactions ([docs](https://github.com/trezor/trezor-firmware/blob/master/core/src/apps/cardano/README.md#multi-sig-transaction))
  - [Script credentials](../blob/276ad461774e78ad8d46d6c9138c2e2cae682b4b/src/js/types/networks/cardano.js#L37-L45) must be used in certificates and withdrawals when signing a multi-sig transaction (using the `MULTISIG_TRANSACTION` signing mode). Ordinary (1852') witness requests are not allowed. All the multisig witness requests (1854') should be provided in the [`additionalWitnessRequests` field](../blob/276ad461774e78ad8d46d6c9138c2e2cae682b4b/src/js/types/networks/cardano.js#L188) in the `cardanoSignTransaction` call and they are all shown to the user. Multisig transaction cannot contain a pool registration certificate.
- token minting and burning ([docs](https://github.com/trezor/trezor-firmware/blob/master/core/src/apps/cardano/README.md#token-mintingburning))
  - There is a new optional [`mint` field](../blob/276ad461774e78ad8d46d6c9138c2e2cae682b4b/src/js/types/networks/cardano.js#L187) in the `cardanoSignTransaction` call. Keys derived from a minting path (1855') are used to create token minting/burning policies. Corresponding witness requests should be provided in the [`additionalWitnessRequests` field](../blob/276ad461774e78ad8d46d6c9138c2e2cae682b4b/src/js/types/networks/cardano.js#L188) in the `cardanoSignTransaction` call and they are all shown to the user.

2021-10-20 13:10 UTC, mroz22 requested changes
Hi, so far looks almost good, almost ready.

2021-10-20 13:10 UTC, mroz22 commented on src/js/types/networks/cardano.js
> +    mintAmount?: string,
hello, some of the changes to this file are not reflected to `networks/cardano.d.ts` maybe you forgot to do so? For example in CardanoToken or CardanoAssetGroup

in general both typescript and flow declarations should be complete.

2021-10-21 08:21 UTC, davidmisiak commented on src/js/types/networks/cardano.js
> +    mintAmount?: string,
Right, sorry for that and thanks for noticing! `CardanoToken` fixed in https://github.com/trezor/connect/pull/920/commits/a7b2cd35a28f4e2e996cf2946c08a1a8e93fb24b. I went through both files and this seems to be the only difference - I haven't found a problem in `CardanoAssetGroup`, they both should be 
```
export type CardanoAssetGroup = {
    policyId: string,
    tokenAmounts: CardanoToken[],
};
```

2021-10-21 08:54 UTC, mroz22 commented
Hi, thanks for resolving my comments. I think we are almost ready to merge it. There is just problem with running tests in browser env (karma). Could you please look at it? at the first glance, I couldn't figure out what might be wrong. 

I can run these tests locally in develop branch using

```
./tests/run.sh -s "yarn test:karma:production" -i getAddress
```

but trying to do the same in your branch fails in a really weird way

2021-10-21 08:54 UTC, mroz22 commented on src/js/types/networks/cardano.js
> +    mintAmount?: string,
ok thanks.

2021-10-21 16:27 UTC, davidmisiak commented
> There is just problem with running tests in browser env (karma). Could you please look at it?

This should be fixed in https://github.com/trezor/connect/pull/920/commits/4e71afedd872d2d6b0d922978d9a2b403b3193bc (the wrong import path apparently prevented all Karma tests from running).

2021-10-22 07:09 UTC, mroz22 commented
Thanks a lot for finding it. We should make it possible to import like you did in the beginning but this is out of the scope of this PR. 

Now please squash your fixups and rebase on latest develop. Then we are ready to go I think.

2021-10-22 07:36 UTC, davidmisiak commented
> Now please squash your fixups and rebase on latest develop. Then we are ready to go I think.

Done.

2021-10-22 08:39 UTC, mroz22 approved these changes
Ready to merge imho. Lets wait a while if @szymonlesisz wants to look at it also.

2021-10-22 16:58 UTC, szymonlesisz commented
looks good and working with older FW as well, thanks guys!

2021-10-22 16:59 UTC, merged

2021-11-01 19:11 UTC, davidmisiak commented
Hi, if my information is correct, there won't be a November release of Trezor firmware and possibly also Trezor Connect. However, we have already implemented multi-sig related changes to cardano-hw-cli (both for Trezor and Ledger) and we would like to release it with multisig support sooner than December (because of Ledger). It would be much simpler for us to include a current Connect build (with multi-sig support) in cardano-hw-cli and release it with a notice, that this release brings multisig functionality only to Ledger users. This way, we wouldn't have to revert our multi-sig changes to the Trezor part of cardano-hw-cli and we would only limit multi-sig functionality in cardano-hw-cli. The new Connect still works with 2.4.2 firmware (just the new functionality is missing), so everything should be fine in this regard. We would create an extended release in our fork of Trezor Connect and include that in cardano-hw-cli until an official release would be made. Would you have any issues with this approach please?

2021-11-03 16:57 UTC, davidmisiak commented
@mroz22 or @szymonlesisz would you have a moment to take a look at this please?

2021-11-04 15:34 UTC, davidmisiak commented
Or do you plan to release Connect sooner than in December (with Trezor Firmware)?