docs(Core): increase delay after RebootToBootloader and fix comment
trezor/connect pull request #972
Opened 2021-12-11 16:02 UTC by tsusanka

See this for rationale https://github.com/trezor/trezor-firmware/issues/1983. There is also a suggestion from @hiviah:

> 501 ms is minimum, 1 s should be OK. Although waiting 501 ms, then doing let's say 5 retry calls to GetFeatures until you get response instead of libusb error spaced 100 ms between each retry would make it slightly faster.

Which would be nice but I think we can leave it with 1s for now.

2021-12-11 16:22 UTC, prusnak requested changes

2021-12-11 16:22 UTC, prusnak commented on src/js/core/Core.js
> +                // This delay is crucial see trezor-firmware#1983
Let's use the full link

```suggestion
                // This delay is crucial see https://github.com/trezor/trezor-firmware/issues/1983
```

2021-12-13 08:42 UTC, prusnak approved these changes

2021-12-13 12:34 UTC, szymonlesisz approved these changes

2021-12-13 12:35 UTC, merged